### ISSUE TITLE
Use for non NVMe PCIe?

### ISSUE THREAD

**Issue by geohot** [cyrozap/usb-to-pcie-re#1]
I'm interested in connecting a GPU to a USB port. We're working on a userspace driver for AMD, so that side of it is handled. https://github.com/tinygrad/tinygrad/pull/6923

What we need is the ability to map the PCIe memory over USB. Do any of the chips you've investigated support this, or is there some reason they only support NVMe? Would much prefer to use one of these chips than need an FPGA.

I'm reading your notes, and it looks like SCSI commands over USB...how much is this baked into the silicon of these chips vs controllable from the firmware?

**Comment by Johnsel** [comment]
Hi @geohot always nice to hear your rants. We've had some chats before about diy neural compute on FPGA.

To answer your question; yes these are USB4 / TBT4/3 to PCIe chips. Intel has a line, AsMedia has another. They basicallly are just transparent except for some security measures. I am working on an open source version of the ASM2464PD(X), which does exactly what you want. USB on one side PCIe (and thus memory map) on the other. 

As discussed on Discord, WIP is underway to build a clone of the ASM2464PDX based converters (no change relevant for you, just allows x4 pcie bifurcation on the output side which allows another board type for me)

**Comment by Johnsel** [comment]
Also see https://github.com/openchips/ASM2464PD-USB4-to-PCIe4-M.2 and a future upcoming JITx based design

**Comment by cyrozap** [comment]
@geohot To clarify, you want to be able to connect a GPU to _any_ computer with USB, regardless of whether that computer supports Thunderbolt or USB4, correct?

The only major limitation of the hardware I'm most familiar with (ASMedia's chips) is that there isn't a way I know of for the bridge IC to efficiently perform large reads and writes to PCI BAR space ("large" here meaning "more than four bytes of data per TLP"), and I assume you'd need that to be able to quickly read and write GPU memory from the host. That said, I'm nowhere near finished reverse engineering these chips, so it's possible they have the hardware to do this and I just haven't found it yet. If that hardware does exist, then the firmware of these chips could (in theory) be modified to convert any PCIe device to USB, GPUs included. But the way the original firmware works is that it expects the PCIe device to perform the data movement to and from the bridge IC, so it's quite possible that the hypothetical "DMA to/from PCI BAR space" hardware doesn't even exist. These chips are very flexible in what they can do, and with the right firmware could probably work with many other types of devices (e.g., NICs, FireWire host controllers, etc.), but to get it working with a GPU would probably also require significant modifications to the GPU driver.

**Comment by geohot** [comment]
@cyrozap Yes. Nice to see you have started on ASM2464PD. I have higher hopes for that chip.

Got it set up tonight, it's on USB 3.2. https://x.com/__tinygrad__/status/1868867387652714522

We have our own userspace GPU driver working, so I'm not worried about that side if we can read/write to the BAR. https://github.com/tinygrad/tinygrad/pull/6923

For speed, at least we can get it working first with 4 byte peeks and pokes. And our GPUs is very capable of DMAing to the bus for fast transfers once it's initted.

**Comment by geohot** [comment]
It sees it, but looks like pcie_mem_dump doesn't work for that chip yet?

```
tiny@usbgpu:~/build/usb-to-pcie-re/ASM2x6x/tools$ ./asm2x6x_tool.py info
Using ASM246X device at "/dev/sg0".
Firmware version: 240229_85_00_00
tiny@usbgpu:~/build/usb-to-pcie-re/ASM2x6x/tools$ ./asm2x6x_tool.py pcie_mem_dump
usage: asm2x6x_tool.py pcie_mem_dump [-h] address length pcie_mem_dump_file
asm2x6x_tool.py pcie_mem_dump: error: the following arguments are required: address, length, pcie_mem_dump_file
tiny@usbgpu:~/build/usb-to-pcie-re/ASM2x6x/tools$ ./asm2x6x_tool.py pcie_mem_dump 0 0x1000 test
Using ASM246X device at "/dev/sg0".
Traceback (most recent call last):
  File "/home/tiny/build/usb-to-pcie-re/ASM2x6x/tools/./asm2x6x_tool.py", line 828, in <module>
    sys.exit(main())
  File "/home/tiny/build/usb-to-pcie-re/ASM2x6x/tools/./asm2x6x_tool.py", line 824, in main
    return args.func(args, dev)
  File "/home/tiny/build/usb-to-pcie-re/ASM2x6x/tools/./asm2x6x_tool.py", line 729, in pcie_mem_dump
    struct.pack_into('<I', buf, buf_idx, dev.pcie_mem_req(start_addr + buf_idx, size=4))
AttributeError: 'Asm246x' object has no attribute 'pcie_mem_req'
```

dump seems fine, flash_dump is implemented but errors

```
tiny@usbgpu:~/build/usb-to-pcie-re/ASM2x6x/tools$ ./asm2x6x_tool.py dump dump_file
Using ASM246X device at "/dev/sg0".
Read 65536 bytes in 0.082103 seconds (798216 bytes per second).
tiny@usbgpu:~/build/usb-to-pcie-re/ASM2x6x/tools$ ./asm2x6x_tool.py flash_dump dump_flash
Using ASM246X device at "/dev/sg0".
Traceback (most recent call last):
  File "/home/tiny/build/usb-to-pcie-re/ASM2x6x/tools/./asm2x6x_tool.py", line 828, in <module>
    sys.exit(main())
  File "/home/tiny/build/usb-to-pcie-re/ASM2x6x/tools/./asm2x6x_tool.py", line 824, in main
    return args.func(args, dev)
  File "/home/tiny/build/usb-to-pcie-re/ASM2x6x/tools/./asm2x6x_tool.py", line 398, in flash_dump
    data = dev.flash_dump(read_len)
  File "/home/tiny/build/usb-to-pcie-re/ASM2x6x/tools/./asm2x6x_tool.py", line 266, in flash_dump
    ret = sgio.execute(self._file, cdb, None, second_data)
  File "src/linux_sgio.pyx", line 177, in sgio.execute
sgio.CheckConditionError: SCSI Check Condition: 700005000000000a00000000240000000000
```

If you try using the functions from Asm236x, you get that same SCSI check condition.

flash dump actually does work, but with a max length of 130816 (dumping 98016 matches the hash of the fw from the internet)

```
tiny@usbgpu:~/build/usb-to-pcie-re/ASM2x6x/tools$ ./asm2x6x_tool.py flash_dump -l 256 temp
Using ASM246X device at "/dev/sg0".
Read 256 bytes in 1.001744 seconds (255 bytes per second).
```

**Comment by geohot** [comment]
So it seems like the write command is failing with that SCSI check condition. Wonder if the MMIO addresses are the same or not? Or if it's the write command itself failing

**Comment by geohot** [comment]
Turns out it works with the ASM23...we need support for the 24, see #2
